baseURL = 'https://www.misterfidget.com/'
languageCode = 'en-us'
title = 'Ethan Estrada'
theme = 'ananke'

# The Raw HTML should always be under my direct control.
ignoreLogs = ['warning-goldmark-raw-html']

# For some reason,
# github only allows publishing from the repo root
# or from a 'docs' directory.
# So, here we are forcing publish to 'docs' even though 'public' makes a lot more sense.
# I can't complain too much.
# It is a free service after all.
publishDir = 'docs'

[security.exec]
allow = [
    '^vi$',
    '^vim$',
    '^nvim$',
    '^(dart-)?sass(-embedded)?$',
    '^go$',
    '^git$',
    '^npx$',
    '^postcss$',
    '^tailwindcss$',
]

[params]
show_reading_time = true

[[params.ananke_socials]]
name = "rss"
url = "/index.xml"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/eestrada"

[[params.ananke_socials]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/1733321/eestrada"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/eestrada_cg"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@EthanEstrada"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/ethan-estrada/"
